appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: F3yGSFMRfA4SQpPTZ50l2XoKU75bzX0fWzgk8USfmWajSwbBnKTjsFgit/ySqYiAi28cKQYsXA8+YQXIVBul6y/qeMjzY1B7gq/vWFwoW35cplJ2ynvF95OqIJ65HnExF911RBPgGnFJp6/I0EGvwJ8wGCLzLlSJ0TRDbJtjp6sGc0CttOjXIfX0b6AiVN/FYXDR6U1Y4O205oQL3wtBc+lL5JP+HB8dh66MVRqtm/ajDUmykIDeaX1Y6ORquJvqLumTGgLBOdlzgPy+/js+gTHrqz0cBC5GQxXE6sYcoGiCLfZNMrR0OcH/SBh2xUdd1u4vker0IV68PCi5A1TidMbFm2XS0POwMbTMT8WlphulnXDRyCJEeADPw6rkMIwgrOt9bljNwPI1qKEu+eA0y+XVnkaIuJljEXLta/1HVxYdfEnwcIqOP9BzQMRKeUItmlTsf18CQkGjIVGqmRW68FE1+d7Ry9wPTIDgZ+lkQ95osw4NPivuADr116U3E/IB3Zi1v5Cyto/zt8OuRN+OsEkB3IbAVzU/Qh2zjX+rKEanZE7PB6N+V10ZrKVvJpiXLPoEN2Q0GwzbxhSA0F5MXfl38PcEi+3hClJrjU/1tnE+cfw3LMCYJT9JpOjkyO2TOwY79Asdrku5v7K6f3dc//MNP5EzSfFGxM4kvJFwhIk=}
conda_forge_output_validation: true
bot:
  automerge: true
